# Generated by Django 4.2.2 on 2023-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='workshops',
            field=models.ManyToManyField(to='workshops.workshops'),
        ),
    ]
