# Generated by Django 4.2.2 on 2023-07-02 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('birth_date', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('especiality', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
