# Generated by Django 4.2.2 on 2023-07-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='gender',
        ),
    ]
